// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: refresh_tokens.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (id, created_at, updated_at, user_id, expires_at, revoked_at)
VALUES(
  $1,
  NOW(),
  NOW(),
  $2,
  $3,
  NULL
)
RETURNING id, created_at, updated_at, user_id, expires_at, revoked_at
`

type CreateRefreshTokenParams struct {
	ID        string
	UserID    uuid.NullUUID
	ExpiresAt sql.NullTime
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, createRefreshToken, arg.ID, arg.UserID, arg.ExpiresAt)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getRefreshTokenById = `-- name: GetRefreshTokenById :one
SELECT id, created_at, updated_at, user_id, expires_at, revoked_at FROM refresh_tokens WHERE id=$1
`

func (q *Queries) GetRefreshTokenById(ctx context.Context, id string) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, getRefreshTokenById, id)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const updateRefreshTokenById = `-- name: UpdateRefreshTokenById :one
UPDATE refresh_tokens
SET
  updated_at = NOW(),
  expires_at = COALESCE($1, expires_at),
  revoked_at = COALESCE($2, revoked_at) 
WHERE 
  id=$3
  AND revoked_at IS NULL
RETURNING id, created_at, updated_at, user_id, expires_at, revoked_at
`

type UpdateRefreshTokenByIdParams struct {
	ExpiresAt sql.NullTime
	RevokedAt sql.NullTime
	ID        string
}

func (q *Queries) UpdateRefreshTokenById(ctx context.Context, arg UpdateRefreshTokenByIdParams) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, updateRefreshTokenById, arg.ExpiresAt, arg.RevokedAt, arg.ID)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const validateRefreshToken = `-- name: ValidateRefreshToken :one
SELECT EXISTS (
    SELECT TRUE
    FROM refresh_tokens
    WHERE id = $1
      AND expires_at >= NOW()
      AND revoked_at IS NULL
) AS is_valid
`

func (q *Queries) ValidateRefreshToken(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRowContext(ctx, validateRefreshToken, id)
	var is_valid bool
	err := row.Scan(&is_valid)
	return is_valid, err
}
